apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: traefik
spec:
  secretName: app-tls
  dnsNames:
    - klaus-devops-journey.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer