version: "3"

tasks:

  load-generator-python:create-image-pull-secret:
    desc: "Create image pull secret to pull from private registry"
    env:
      DOCKER_USERNAME:
      DOCKER_EMAIL:
      DOCKER_PASSWORD:
    cmds:
      - |
        if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_EMAIL" ] || [ -z "$DOCKER_PASSWORD" ]; then
          echo "Environment variables DOCKER_USERNAME, DOCKER_EMAIL, and DOCKER_PASSWORD are required."
          exit 1
        fi
      - |
        kubectl create secret -n demo-app docker-registry dockerconfigjson \
          --docker-email=${DOCKER_EMAIL} \
          --docker-username=${DOCKER_USERNAME} \
          --docker-password=${DOCKER_PASSWORD} \
          --docker-server=https://index.docker.io/v1/
  apply-all-workload-manifests:
    cmds: 
    - kubectl apply -f api-golang/.
    - kubectl apply -f api-node/.
    - kubectl apply -f client-react/.
  