apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cnpg-db-store
spec:
  provider:
    kubernetes:
      remoteNamespace: db
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: db          # required for ClusterSecretStore — no implicit namespace context like a namespaced SecretStore has
      auth:
        serviceAccount:
          name: cnpg-secret-reader
          namespace: demo-app