apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-database-url
  namespace: demo-app
spec:
  secretStoreRef:
    name: cnpg-db-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: postgres-database-url
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: cnpg-minimal-app
        property: uri