apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.klaus-devops-journey.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer