apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://k8s-learning-kv.vault.azure.net"
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets