apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example-azure
  namespace: external-secrets
spec:
  refreshInterval: 1h # rate Key Vault is polled
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store # name of the SecretStore (or kind specified)
  target:
    name: external-secrets-example-k8s-azure # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: key-k8s # key in the Kubernetes Secret
      remoteRef:
        key: external-secrets-example-azure # name of the Key Vault secret