apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: <AZURE_IDENTITY_CLIENT_ID> ## managed identity client id
  labels:
    azure.workload.identity/use: "true"