load('ext://ko', 'ko_build')
ko_build(
  'klausanders444/kubernetes-learning-api-golang', 
  './',
  deps=['.']
)
k8s_yaml('../../03-Project-manifests/api-golang/Deployment.yaml')
k8s_resource('api-golang', port_forwards=8000)